### PR TITLE
Fix word count to query other instances

### PR DESCRIPTION
**Pull request by bbejeck**

### CODE REVIEW

**Comment by bbejeck** [comment]
@dguy @guozhangwang @mjsax @miguno 

Updated the example to query across instances for individual word counts

**Comment by guozhangwang** [comment]
@bbejeck Since the user reported seeing this issue in 3.3.0 also, should we submit the PR against 3.3.0-post and merge all the way down to other branches?

**Comment by bbejeck** [comment]
Yes.  I overlooked the fact that is was in 3.3.0-post as well.

**Comment by mjsax** [comment]
@bbejeck No need to close and reopen a new PR -- you can also change the target branch for the PR. Just FYI.

**Pull request closed without merging**
