### PR TITLE
Fix for compilation failure due to missing AVRO generated sources

### PR DESCRIPTION
**Pull request by ajithprasadanand**

### CODE REVIEW

**Comment by ajithprasadanand** [comment]
@mjsax  Ready to Merge

**Comment by mjsax** [comment]
Thanks for the PR. Can you open the PR against `3.3.0-post` branch instead of `4.0.0.-post` ?

**Comment by ajithprasadanand** [comment]
@mjsax  Switched the branch.

**Comment by mjsax** [comment]
@ajithprasadanand Thanks. Seems you need to cleanup the PR. Just swithcing the branch would pull in many other commits from `4.0.0-post` into `3.3.0-post` that should not go into `3.0.0-post` though :(

**Comment by ajithprasadanand** [comment]
@mjsax Should I close this PR and create a fresh PR on 3.3.0-post ?

**Comment by mjsax** [comment]
@ajithprasadanand Whatever is simpler for you.

**Pull request closed without merging**
