### PR TITLE
Add warning re TopFiveSongs aggregator

### PR DESCRIPTION
**Pull request by benissimo**
See discussion on https://issues.apache.org/jira/browse/KAFKA-12446
and https://github.com/confluentinc/kafka-streams-examples/issues/380

### CODE REVIEW

**Comment by mjsax** [comment]
Thanks for the PR -- can we direct the PR to `6.2.x` branch so it goes live with `6.2.0` release? Or maybe even `6.1.0-post` to get it live current examples? -- If you don't care, I can also merge as-is, but it would only go live with 6.3.0 release than.

**Comment by benissimo** [comment]
@mjsax Sure, whichever target branch makes the most sense. Feel free to change as needed. Please let me know if there's anything I can do to help.

**Comment by mjsax** [comment]
> Feel free to change as needed. 

Well I tried this but it pulls in other commit from other branches -- you would need to rebase this PR on the new target branch... Can you do this? (If rebasing does not work, just close this PR and do a new one).

I would propose to use `6.1.0-post` as target branch.

Thank you!

**Comment by benissimo** [comment]
I created a new branch, based on 6.1.0-post, and cherry-picked my commit onto it: https://github.com/confluentinc/kafka-streams-examples/pull/384 cc @mjsax

**Pull request closed without merging**
