### PR TITLE
MINOR: fix pom for Eclipse

### PR DESCRIPTION
**Pull request by mjsax**
This is a cleanup for #99

### CODE REVIEW

**Comment by mjsax** [comment]
There was no further response on #99 so I opened this...

**Comment by mjsax** [comment]
\cc @ajithprasadanand

**Comment by mjsax** [comment]
@bbejeck The build failed with
```
[ERROR] /home/****/workspace/fka-streams-examples_PR-102-3MNRSCXHSUDN25ZUJID3UYKBBERCJKI6EHYR2JYEV2VLC34EHF2Q/src/test/java/io/confluent/examples/streams/kafka/EmbeddedSingleNodeKafkaCluster.java:[107,19] cannot find symbol
```

Seems to be your latest commit... Any insights?

**Comment by bbejeck** [comment]
@mjsax I'll look into it

**Comment by mjsax** [comment]
Updated this.

**Pull request merged**
