### PR TITLE
Add Dotnet Stream examples

### PR DESCRIPTION
**Pull request by LGouellec**
The aims of this PR is to provide some kafka streams examples for Dotnet implementation.

I create a dotnet folder which contains samples implementation with a real cluster, and tests implementation with TopologyTestDriver. 

All samples are not completed yet, because dotnet implementation is not finished yet !

### CODE REVIEW

**Comment by LGouellec** [comment]
Are you waiting for more information on this PR ?

**Comment by ableegoldman** [comment]
Hey @LGouellec ,

Thanks for sending over this patch! We really appreciate it, and it looks pretty cool. I'm not sure it quite belongs here, though; the purpose of this repository is to demonstrate examples of the Java version of Kafka Streams, and we're really just trying to do one thing well. It seems like these examples would merit a repository of their own that's focused on .NET examples?

**Comment by LGouellec** [comment]
Key @ableegoldman, 

You are definitely right ! Maybe we have to wait all final features in Kafka Streams .NET package (miss persistent state store, replication & changelog topics) to create a repository focused on .NET examples.

Regards,

**Comment by mjsax** [comment]
@LGouellec Seems you agree that a dedicated repository would be better. Can we close this PR?

**Comment by LGouellec** [comment]
@mjsax , Yeah you can close this PR :) Thanks for your time.

**Pull request closed without merging**
