### PR TITLE
Compilation failure of all the classes which are dependent on "Avro generated sources" due to "Avro generated sources" missing in the build path

### PR DESCRIPTION
**Pull request by ajithprasadanand**

### CODE REVIEW

**Comment by mjsax** [comment]
@ajithprasadanand Thanks for the PR. It contains more than one commit. Did you branch from `3.3.0-post`? If yes, you might need to rebase to `3.3.0-post` to get rid of old commits. This PR should only have a single commit with your changes.

Thanks a lot!

**Comment by mjsax** [comment]
@ajithprasadanand Are you still working on this? We would like to get this improvement. But you need to branch off `3.3.0-post`, do a single commit and update this PR (or open a new one). Atm, we cannot merge this PR because it contains changes that do not belong into `3.3.0-post` branch.

**Comment by ajithprasadanand** [comment]
@mjsax Sorry I somehow missed this task. I will do it tomorrow.

**Comment by mjsax** [comment]
No need to apologize :) Thanks a lot for contributing!

**Comment by ajithprasadanand** [comment]
@mjsax New PR from 3.3.0-post created. Closing this One. Please check.

**Comment by mjsax** [comment]
Thanks a lot!

**Pull request closed without merging**
