### PR TITLE
Examples now in a Table

### PR DESCRIPTION
**Pull request by danielccyr**
easier to understand

### CODE REVIEW

**Comment by danielccyr** [comment]
[clabot:check]

**Comment by guozhangwang** [comment]
cc @dguy

**Comment by dguy** [comment]
@miguno

**Comment by miguno** [comment]
LGTM, thanks @danielccyr !

**Comment by miguno** [comment]
Note: This PR would also need to be merged into the `4.1.x` and `master` branches.

**Comment by mjsax** [comment]
Thanks for the PR @danielccyr !

**Pull request merged**
