### PR TITLE
MINOR: Fixes for compilation errors

### PR DESCRIPTION
**Pull request by bbejeck**
Changes needed due to upstream changes.

### CODE REVIEW

**Comment by bbejeck** [comment]
Build is failing with
```
[2019-09-27T19:04:56.224Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project kafka-streams-examples: Compilation failure
[2019-09-27T19:04:56.224Z] [ERROR] /home/****/workspace/pr_kafka-streams-examples_PR-293/src/test/java/io/confluent/examples/streams/GenericAvroIntegrationTest.java:[134,34] cannot infer type arguments for io.confluent.kafka.serializers.KafkaAvroDeserializer
[2019-09-27T19:04:56.224Z] [ERROR]   reason: cannot use '<>' with non-generic class io.confluent.kafka.serializers.KafkaAvroDeserializer
```
But it passes locally for me and `5.4.x` `KafkaAvroDeserializer` is a generic class

**Comment by apurvam** [comment]
Yea, there were a bunch of upstream changes were made to SR that is causing this to break. If you clear your local caches, it may fail for you locally too.

**Comment by mjsax** [comment]
Seems this relates to some SR changes: https://github.com/confluentinc/schema-registry/pull/1111/files#diff-7b9023c11002822280539ef723ea4736R26

Reverted via: https://github.com/confluentinc/schema-registry/pull/1214

So maybe we don't need this PR any longer?

**Comment by apurvam** [comment]
It seems the build is still failing on jenkins though.

**Comment by bbejeck** [comment]
I kicked off a new build and it now compiles.  Waiting for the tests to finish, I have seen some failures on my local with the microservices tests, that's what took so long for me to push this PR.

I think we should keep if the generic parameters go back in then we can simply merge this.

**Comment by mjsax** [comment]
Build failed with compile error (due to SR revert PR?):

```
[2019-09-27T19:04:57.282Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project kafka-streams-examples: Compilation failure
[2019-09-27T19:04:57.282Z] [ERROR] /home/****/workspace/rs_kafka-streams-examples_PR-293/src/test/java/io/confluent/examples/streams/GenericAvroIntegrationTest.java:[134,34] cannot infer type arguments for io.confluent.kafka.serializers.KafkaAvroDeserializer
[2019-09-27T19:04:57.282Z] [ERROR]   reason: cannot use '<>' with non-generic class io.confluent.kafka.serializers.KafkaAvroDeserializer
```

**Comment by bbejeck** [comment]
>Build failed with compile error (due to SR revert PR?):

Yep, I kicked off a new `master` build and everthing compiles, but we have failing microservices tests
```
EndToEndTest.startEverythingElse:185->lambda$startEverythingElse$1:185 » Runtime
EndToEndTest.startEverythingElse:185->lambda$startEverythingElse$1:185 » Runtime
EndToEndTest.startEverythingElse:185->lambda$startEverythingElse$1:185 » Runtime
ValidationsAggregatorServiceTest.shouldAggregateRuleSuccesses:65 »
```

Looking into why these are failing

**Pull request closed without merging**
