### PR TITLE
DEVX-544: dynamic routing example

### PR DESCRIPTION
**Pull request by ybyzek**
The goal of this PR is to show dynamic routing using TopicNameExtractor

This PR also fixes https://github.com/confluentinc/kafka-streams-examples/issues/189

### CODE REVIEW

**Comment by mjsax** [comment]
@ybyzek Should this target 5.0.0-post? Dynamic routing was added in 2.0/5.0 release.

**Comment by ybyzek** [comment]
> @ybyzek Should this target 5.0.0-post? Dynamic routing was added in 2.0/5.0 release.

@mjsax in theory it could have, but it needs to stay in sync with the corresponding changes going into [another repo with this PR](https://github.com/confluentinc/examples/pull/102) .  As long as we have an example to point to, even going into 5.1.0-post, I think it's ok.  WDYT?

**Comment by mjsax** [comment]
Ack. Fine with me to only have it for 5.1 :)

**Comment by miguno** [comment]
@ybyzek : Thanks so much.  Could you please also update the top-level `README.md` so that other users can easily find the new example along side the other examples?  See https://github.com/confluentinc/kafka-streams-examples#available-examples.  I'd use words like "message routing", "dynamic routing" for the "Concepts used" column, for instance.

**Comment by ybyzek** [comment]
@miguno 👍

**Pull request merged**
