### PR TITLE
Fix class name in javadoc

### PR DESCRIPTION
**Pull request by VenkataKotra**

### CODE REVIEW

**Comment by miguno** [comment]
Thanks @VenkataKotra .  Could you please sign our CLA (see auto-generated comment above)?  We require this step for legal reasons, unfortunately.

**Comment by albertostratio** [comment]
@VenkataKotra I submitted a PR fixing this issue: [fix javadoc](https://github.com/confluentinc/kafka-streams-examples/pull/7)

**Comment by VenkataKotra** [comment]
Thanks @albertostratio

**Comment by VenkataKotra** [comment]
@miguno - CLA signed. [clabot:check]

**Pull request merged**
