### PR TITLE
logging config: DEBUG -> INFO

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by guozhangwang** [comment]
@sullis could you elaborate the motivation to change default logging level to INFO?

**Comment by mjsax** [comment]
What is the status of this? Should this PR be closed?

**Comment by miguno** [comment]
@mjsax:
> We recently intentionally increase the log level to DEBUG -- sometimes some tests fails (due to race conditions) and having DEBUG level logs give us valuable information to fix those tests.

Shouldn't we rather update our build (Jenkins) to override the log level, rather than exposing every user to the flood of DEBUG messages?

**Comment by mjsax** [comment]
\cc @guozhangwang @bbejeck @vvcephei Any comments?

**Comment by guozhangwang** [comment]
I'm not sure how to change the jenkins settings to override log levels, but assuming it is doable I'm fine with changing it back to INFO.

**Comment by guozhangwang** [comment]
@sullis I'm going to merge this PR and explore other ways to enable efficient trouble shooting.

**Pull request merged**
