### PR TITLE
use 'https' for Maven repo

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
please merge

**Comment by mjsax** [comment]
Call for review @confluentinc/tools

**Comment by mjsax** [comment]
@maxzheng Should we back port this to `3.3.0-post` ?

**Comment by maxzheng** [comment]
@mjsax that's up to you since you are the owner. ;)

**Comment by mjsax** [comment]
Thanks @maxzheng :) Will do. And thanks for reviewing/merging!

**Comment by mjsax** [comment]
Thanks for the patch @sullis !

**Pull request merged**
